// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY-JQEEk2oNYTwW9uqcbBD67m4miGofdA',
    appId: '1:650016222985:web:a42f47c83bac25b86dedd8',
    messagingSenderId: '650016222985',
    projectId: 'meatshop-3c78f',
    authDomain: 'meatshop-3c78f.firebaseapp.com',
    storageBucket: 'meatshop-3c78f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzNpWnPO-Vxotx6IrS7959TbVwfRc2Otc',
    appId: '1:650016222985:android:8036544d9b010f256dedd8',
    messagingSenderId: '650016222985',
    projectId: 'meatshop-3c78f',
    storageBucket: 'meatshop-3c78f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCTUKIc-ldWFUfYX6gTrSA0y9R_b_GB8Y',
    appId: '1:650016222985:ios:0f005885bfde5c6d6dedd8',
    messagingSenderId: '650016222985',
    projectId: 'meatshop-3c78f',
    storageBucket: 'meatshop-3c78f.firebasestorage.app',
    iosBundleId: 'com.example.meatshopMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCTUKIc-ldWFUfYX6gTrSA0y9R_b_GB8Y',
    appId: '1:650016222985:ios:0f005885bfde5c6d6dedd8',
    messagingSenderId: '650016222985',
    projectId: 'meatshop-3c78f',
    storageBucket: 'meatshop-3c78f.firebasestorage.app',
    iosBundleId: 'com.example.meatshopMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY-JQEEk2oNYTwW9uqcbBD67m4miGofdA',
    appId: '1:650016222985:web:ae1f8b9014e7e08f6dedd8',
    messagingSenderId: '650016222985',
    projectId: 'meatshop-3c78f',
    authDomain: 'meatshop-3c78f.firebaseapp.com',
    storageBucket: 'meatshop-3c78f.firebasestorage.app',
  );
}
